### ISSUE TITLE
using flutter pay u money release build failed 

### ISSUE THREAD

**Issue by undamatlamanikanta** [ditheshthegreat/flutter_pay_u_money#1]
Execution failed for task ':flutter_pay_u_money:verifyReleaseResources'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

**Comment by ditheshthegreat** [comment]
> Execution failed for task ':flutter_pay_u_money:verifyReleaseResources'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

Can u give me the full log
